require_relative 'advanced_math/abstract_vector'
require_relative 'advanced_math/vector'
require_relative 'advanced_math/row_vector'
require_relative 'advanced_math/column_vector'
require_relative 'advanced_math/mutable_vector'
require_relative 'advanced_math/abstract_matrix'
require_relative 'advanced_math/matrix'
require_relative 'advanced_math/mutable_matrix'
require_relative 'advanced_math/square_matrix'
require_relative 'advanced_math/row_matrix'
require_relative 'advanced_math/square_row_matrix'
require_relative 'advanced_math/column_matrix'
require_relative 'advanced_math/square_column_matrix'
require_relative 'advanced_math/lu_decomposition'
require_relative 'advanced_math/sle'

module AdvancedMath; end
