require_relative 'lu_decomposition/find_main_element_row_index'
require_relative 'lu_decomposition/abstract_form'
require_relative 'lu_decomposition/sequential_services'
require_relative 'lu_decomposition/parallel_services'

module LUDecomposition; end
